INSERT INTO public.mushroom_location (name, x, y, description) VALUES
                                                            ('Agaricus bisporus', 45.4215, -75.6972, 'Also known as the white button mushroom, commonly found in North America and Europe. Used in many dishes.'),
                                                            ('Boletus edulis', 46.603354, 1.888334, 'The king bolete is a popular and sought-after wild mushroom. It grows in various parts of Europe.'),
                                                            ('Amanita muscaria', 58.5950, 25.0136, 'Known as the fly agaric. Iconic red and white mushroom. Common in Estonian forests.'),
                                                            ('Cantharellus cibarius', 56.4907, -4.2026, 'The golden chanterelle, commonly found across Europe.'),
                                                            ('Tricholoma matsutake', 36.2048, 138.2529, 'A rare and expensive mushroom found mainly in Japan.'),
                                                            ('Lactarius deliciosus', 40.4637, -3.7492, 'The saffron milk cap, found across Europe especially in Spain.'),
                                                            ('Morchella esculenta', 58.5951, 25.0136, 'Morel mushroom, often found in Estonian forests during spring.'),
                                                            ('Psilocybe semilanceata', 53.349805, -6.26031, 'Magic mushroom. Common in Europe, especially Ireland.'),
                                                            ('Pleurotus ostreatus', 51.1657, 10.4515, 'Oyster mushroom. Widely cultivated and found in the wild across Europe, especially Germany.'),
                                                            ('Calvatia gigantea', 52.3555, 1.1743, 'The giant puffball. Common in meadows and fields across Europe.'),
                                                            ('Russula emetica', 64.2008, -149.4937, 'The sickener. Found in coniferous forests in Northern America.'),
                                                            ('Stropharia rugosoannulata', 47.1625, 19.5033, 'Wine cap stropharia. Found across Europe and especially Hungary.'),
                                                            ('Coprinus comatus', 52.1326, 5.2913, 'The shaggy ink cap or lawyer''s wig. Found across Europe and especially the Netherlands.'),
                                                            ('Hydnum repandum', 58.5952, 25.0136, 'Hedgehog mushroom. Common in Estonian forests.'),
                                                            ('Cortinarius caperatus', 60.1282, 18.6435, 'The gypsy mushroom. Found in Northern Europe, especially Sweden.'),
                                                            ('Suillus luteus', 56.2639, 9.5018, 'Slippery jack. Common across Europe, especially Denmark.'),
                                                            ('Armillaria mellea', 50.5039, 4.4699, 'Honey fungus. Grows on trees and woody shrubs across Europe, especially Belgium.'),
                                                            ('Laccaria amethystina', 48.0196, 66.9237, 'The amethyst deceiver. Found across Europe and parts of Asia, especially Kazakhstan.'),
                                                            ('Tricholomopsis rutilans', 58.5954, 25.0136, 'Plums and custard. Commonly found in coniferous woods in Estonia.'),
                                                            ('Flammulina velutipes', 37.5665, 126.9780, 'Enoki mushroom. Wild versions found across Asia, especially South Korea.'),
                                                            ('Lactarius torminosus', 58.5955, 25.0136, 'Woolly milkcap. Common in Estonian forests.'),
                                                            ('Russula aeruginea', 58.5956, 25.0136, 'Green russula. Commonly found in Estonia during summer.'),
                                                            ('Amanita phalloides', 48.8566, 2.3522, 'Death cap. One of the most toxic mushrooms, found across Europe, especially France.'),
                                                            ('Suillus grevillei', 58.5957, 25.0136, 'Larch bolete. Found in Estonian coniferous woods.'),
                                                            ('Claviceps purpurea', 58.5953, 25.0136, 'Ergot fungus. Found on rye and related plants in Estonia.'),
                                                            ('Russula vesca', 50.8503, 4.3517, 'Bare-toothed russula. Common across Europe, especially Belgium.'),
                                                            ('Lepista nuda', 58.5958, 25.0136, 'Wood blewit. Found in both coniferous and deciduous forests in Estonia.'),
                                                            ('Marasmius oreades', 53.1424, -7.6921, 'Fairy ring mushroom. Common across Europe, especially Ireland.'),
                                                            ('Paxillus involutus', 58.5959, 25.0136, 'Brown roll-rim. Common in Estonia and poisonous.'),
                                                            ('Boletus badius', 51.9194, 19.1451, 'Bay bolete. Widely distributed across Europe, especially Poland.'),
                                                            ('Agaricus augustus', 58.5953, 25.0130, 'The prince. Found in Estonia during summer and early autumn.'),
                                                            ('Lactarius helvus', 58.5953, 25.0131, 'The fenugreek milkcap. Common in Estonian coniferous forests.'),
                                                            ('Amanita fulva', 58.5953, 25.0132, 'Tawny grisette. Commonly found in Estonian forests.'),
                                                            ('Russula decolorans', 46.8182, 8.2275, 'Changing russula. Common in parts of Europe, especially Switzerland.'),
                                                            ('Lactarius deterrimus', 58.5953, 25.0133, 'False saffron milkcap. Common in Estonian forests.'),
                                                            ('Lycoperdon perlatum', 55.1694, 23.8813, 'Common puffball. Found across Europe, especially Lithuania.'),
                                                            ('Tricholoma sulphureum', 55.9533, -3.1883, 'Sulphur knight. Widely distributed across Europe, especially Scotland.'),
                                                            ('Amanita rubescens', 58.5953, 25.0134, 'The blusher. Common in Estonia and many parts of Europe.'),
                                                            ('Russula integra', 58.5953, 25.0135, 'Entire russula. Found in Estonian woods during summer.'),
                                                            ('Lactarius uvidus', 58.5953, 25.0136, 'Brandy milkcap. Common in Estonian forests during autumn.'),
                                                            ('Tallinn', 59.43656998937416, 24.751016910523873, 'feature 1 in Estonian forests during autumn.'),
                                                            ('Väo karjäär', 59.42713690675782, 24.774741679964393, 'Ülemiste järvevana  in Estonia.'),
                                                            ('rändom', -159.42713690675782, -124.774741679964393, 'rändom test.');